name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm
    - run: npm ci
    - run: xvfb-run -a npm test
      name: Test
      if: runner.os == 'Linux'
    - run: npm test
      name: Test
      if: runner.os != 'Linux'
    - run: |
        timestamp=$(date +%Y%m%d%H%M%S)
        version=$(npm pkg get version | sed 's/\"//g')
        npm pkg set version="$version-next+$timestamp"
    - run: npm run package -- --pre-release
    - name: Preserve VSIX package
      uses: actions/upload-artifact@v3
      with:
        name: vsix
        path: '*.vsix'
        retention-days: 1
